<a href="https://colab.research.google.com/github/gianmarcomejia96/UTEC_PROGRA/blob/main/03_estructuras_de_datos_parte2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


<img src="https://www.ctic.uni.edu.pe/wp-content/uploads/2022/04/588px-x-348px-web-1.png" alt="HTML5 Icon" width="900" height="350" >


<h1 align=center><font size = 5>ESTRUCTURAS DE DATOS - PARTE 2
</font></h1>

---


**Tabla de Contenidos**

- Diccionarios
- Sets
- Matrices

---

## 1. Diccionarios

**Concepto:**

Un diccionario es una estructura de datos que almacena pares clave-valor. Las claves deben ser únicas y se utilizan para acceder a los valores asociados.

### Ejemplo 1.1: Creación de Diccionarios y Acceso a Elementos


In [ ]:
# Crear un diccionario
persona = {'nombre': 'Ana', 'edad': 30, 'ciudad': 'Lima'}
print(persona)

{'nombre': 'Ana', 'edad': 30, 'ciudad': 'Lima'}


In [ ]:
persona = {'nombre':'Gianmarco','edad':30,'ciudad':'Lima'}

persona['nombre']

del persona['nombre']

persona

persona['nombre'] = 'Gianmarco'

persona

persona.get('Gianmarco')

In [ ]:
persona.get('edad')

30

In [ ]:
# Acceder a un valor
print("Nombre:", persona['nombre'])
print("Ciudad:", persona.get('ciudad'))


Nombre: Gianmarco
Ciudad: Lima


In [ ]:

# Añadir un nuevo par clave-valor
persona['profesion'] = 'Ingeniera'
print(persona)



In [ ]:
# Eliminar un par clave-valor
del persona['ciudad']
print(persona)

{'edad': 30, 'nombre': 'Gianmarco'}


### Ejemplo 1.2: Métodos Útiles de Diccionarios


In [ ]:
# Obtener todas las claves
print(persona.keys())


dict_keys(['edad', 'ciudad', 'nombre'])


In [ ]:
# Obtener todos los valores
print(persona.values())


dict_values([30, 'Lima', 'Gianmarco'])


dict_values([30, 'Lima', 'Gianmarco'])

In [ ]:
features_describe = {'pas_avg12': 'Ahorros promedio de la persona en los últimos meses', 'age':'Edad de la persona recogida de reniec','dist':'Distrito de residencia declarado por el cliente en última llamada'}

In [ ]:
features_describe['age']

'Edad de la persona recogida de reniec'

In [ ]:
persona.items()

dict_items([('edad', 30), ('nombre', 'Gianmarco')])

In [ ]:
for key, value in persona.items():
    print(key,value)

edad 30
nombre Gianmarco


In [ ]:
resumen = {
    "edad": 35.6,
    "ingreso": 10500.0,
    "hijos": 2.1
}

In [ ]:
for key, value in resumen.items():
  print(f' el promedio de {key} es: {value}')

 el promedio de edad es: 35.6
 el promedio de ingreso es: 10500.0
 el promedio de hijos es: 2.1


In [ ]:
template = "Hola {nombre}, tu edad es {edad} y vivís en {ciudad}."
datos = {
    "nombre": "Luis",
    "edad": 30,
    "ciudad": "Córdoba"
}

for key,value in datos.items():
    template = template.replace("{"+ key + "}",str(value))

template

'Hola Luis, tu edad es 30 y vivís en Córdoba.'

In [ ]:
template.format(**datos)

'Hola Luis, tu edad es 30 y vivís en Córdoba.'

In [ ]:
# Comprobar si una clave existe en el diccionario
if 'edad' in persona:
    print("La clave 'edad' está en el diccionario.")





La clave 'edad' está en el diccionario.


In [ ]:
persona['edad']

30

### Ejercicio 1: Trabajando con Diccionarios

- Crea un diccionario que contenga información sobre un automóvil (marca, modelo, año, color).
- Accede a cada valor usando su clave.
- Añade una clave para el precio del automóvil.
- Elimina la clave del color del automóvil y muestra el diccionario actualizado.
- Usa keys() y values() para imprimir las claves y valores del diccionario.



In [ ]:
automovil = {'marca':'changan','modelo':'cs35 plus','color':'blanco'}

automovil.values()
automovil.keys()

print(f'estas son {automovil['marca']} {automovil['modelo']} {automovil['color']}')

automovil['precio'] = 18000

automovil.values()

del automovil['color']

automovil

for key, value in automovil.items():
  print(f' el diccionario contiene {key} : {value}')


estas son changan cs35 plus blanco
 el diccionario contiene marca : changan
 el diccionario contiene modelo : cs35 plus
 el diccionario contiene precio : 18000


## 2. Sets

Los sets son colecciones de elementos únicos y desordenados. Son útiles para eliminar duplicados o realizar operaciones matemáticas como intersección y unión.

### Ejemplo 2.1: Creación y Modificación de Sets

In [ ]:
# Crear un set
numeros = {1, 2, 3, 4, 5}
print(numeros)


{1, 2, 3, 4, 5}


In [ ]:
my_set = {1,2,3,4}


my_set2 = set((1,2,3,5))

print(my_set)
print(my_set2)

lista = [1,1,2,3]

lista_set = set(lista)

print(lista_set)


{1, 2, 3, 4}
{1, 2, 3, 5}
{1, 2, 3}


In [ ]:
lista = ['aa','aa']

set_lista = set((lista))

print(set_lista)

list(set_lista)
print(set_lista)

{'aa'}
{'aa'}


In [ ]:
lista_1 = ['columna1', 'columna2', 'columna3']
lista_2 = ['columna1', 'columna2', 'columna5']


list(set(lista_1+lista_2))


['columna3', 'columna1', 'columna2', 'columna5']

In [ ]:
# Añadir elementos
numeros.add(6)
print(numeros)


{1, 2, 4, 5, 6}


In [ ]:
# Eliminar un elemento
numeros.remove(2)
print(numeros)


{1, 4, 5, 6}


### Ejemplo 2.2: Operaciones de Conjuntos


In [ ]:
# Crear otro set
otro_set = {4, 5, 6, 7}

In [ ]:
# Unión de sets (todos los elementos)
union = numeros.union(otro_set)
print("Unión:", union)


Unión: {1, 4, 5, 6, 7}


In [ ]:
# Intersección de sets (elementos comunes)
interseccion = numeros.intersection(otro_set)
print("Intersección:", interseccion)


Intersección: {4, 5, 6}


### Ejercicio 2: Operaciones con Sets

- Crea dos sets de números: uno con números del 1 al 10 y otro con números del 5 al 15.
- Encuentra la intersección y unión de ambos sets.
- Elimina un número del primer set.
- Usa un set para almacenar los nombres de tus amigos. Asegúrate de que no haya duplicados.

In [ ]:

lista_1 = list(set([x for x in range(1,11)]))

lista_2 = list(set([x for x in range(5,16)]))

print(lista_1)
print(lista_2)

lista_1.remove(2)
lista_1

nombres = []

while True:
    nombre = input('ingrese nombres: ')
    if nombre == 'exit':
      break
    else:
     nombres.append(nombre)




[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
ingrese nombres: carlos
ingrese nombres: gian
ingrese nombres: omar
ingrese nombres: juan
ingrese nombres: gian
ingrese nombres: carlos
ingrese nombres: exit


In [ ]:
nombres

nombres_finales = set(nombres)

nombres_finales

{'carlos', 'gian', 'juan', 'omar'}

## 3. Matrices

En Python, las matrices pueden representarse como listas de listas. Para manipular matrices más avanzadas y realizar cálculos eficientes, utilizamos la librería NumPy.

### Ejemplo 3.1: Matrices con Listas de Listas


In [ ]:
# Crear una matriz 3x3 con listas anidadas
matriz = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
print(matriz)


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [ ]:
# Acceder a elementos de la matriz
print("Elemento en [1][1]:", matriz[1][1])

matriz[1][2] = 2

matriz


Elemento en [1][1]: 5


[[1, 2, 3], [4, 5, 2], [10, 8, 9]]

In [ ]:
}# Modificar un elemento
matriz[2][0] = 10
print(matriz)

[[1, 2, 3], [4, 5, 6], [10, 8, 9]]


### Ejemplo 3.2: Manipulación de Matrices con NumPy


In [ ]:
import numpy as np

# Crear una matriz 3x3 con NumPy
matriz_np = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(matriz_np)




[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Sumar 10 a cada elemento
print(matriz_np + 10)



[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [ ]:
# Multiplicar cada elemento por 2
print(matriz_np * 2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


### Ejercicio 3: Operaciones con Matrices

- Crea una matriz 3x3 usando listas de listas.
- Modifica un valor de la matriz y muestra la matriz actualizada.
- Usa NumPy para crear una matriz 4x4 con números aleatorios enteros.
- Realiza una operación de suma con la matriz (suma 5 a cada elemento).
- Multiplica los elementos de la matriz por 2 usando NumPy.

In [3]:
import numpy as np

In [6]:
import numpy as numpy

In [14]:
matriz = np.random.randint(0, 10, size=(4, 3,2))
print(matriz)


[[[0 0]
  [1 1]
  [9 3]]

 [[9 2]
  [0 4]
  [5 0]]

 [[5 8]
  [1 2]
  [4 8]]

 [[3 9]
  [2 7]
  [4 8]]]


In [15]:
valores = np.array([10, 25, 35, 60, 90])

📊 Ejercicio 1: Normalización de datos

Tienes este array:

valores = np.array([10, 25, 35, 60, 90])


👉 Normaliza los valores para que estén entre 0 y 1.
(Fórmula: (x - min) / (max - min))

In [19]:
minimo = np.min(valores)
maximo = np.max(valores)

normalizado = []

for i in valores:
  normal = (i - minimo)/(maximo - minimo)
  normalizado.append(normal)





In [21]:
normalizado2 = (valores - minimo) / (maximo - minimo)

In [22]:
normalizado2

array([0.    , 0.1875, 0.3125, 0.625 , 1.    ])

📉 Ejercicio 2: Filtrado de datos

Crea una matriz 6x4 con números aleatorios entre 0 y 100.
👉 Luego, extrae solo las filas donde todos los números son mayores a 50.

In [30]:
matriz = np.random.randint(0,100,size = (6,4))

matriz

array([[82, 93, 35, 82],
       [44, 72, 13, 30],
       [13, 34, 85, 98],
       [15, 25, 40, 36],
       [79, 18, 20, 23],
       [84, 65, 83, 73]])

In [26]:
lista = matriz > 50

In [42]:
filtro = np.all(matriz>50,axis=1)
filtro

array([False, False, False, False, False,  True])

In [43]:
filtro
filtradas = matriz[filtro]
filtradas

array([[84, 65, 83, 73]])

📈 Ejercicio 3: Promedios por columna

Crea una matriz 5x3 con números aleatorios entre 10 y 500.
👉 Calcula el promedio de cada columna.
Luego, resta ese promedio a cada valor de su columna.

In [47]:
matriz = np.random.randint(10,50,size=(5,3))

matriz

array([[16, 12, 16],
       [43, 23, 19],
       [17, 44, 11],
       [31, 31, 19],
       [39, 17, 31]])

In [48]:
promedio = np.average(matriz,axis=0)


array([29.2, 25.4, 19.2])

In [52]:
nuevos = abs(matriz - promedio)

nuevos

array([[13.2, 13.4,  3.2],
       [13.8,  2.4,  0.2],
       [12.2, 18.6,  8.2],
       [ 1.8,  5.6,  0.2],
       [ 9.8,  8.4, 11.8]])

In [27]:
lista

array([[[ True,  True, False, False],
        [ True, False, False, False],
        [False, False,  True, False],
        [ True, False,  True,  True],
        [ True, False,  True, False],
        [ True, False, False, False]]])

In [53]:
matriz = np.random.randint(50, 151, size=(100, 5))

In [54]:
q1 = np.percentile(matriz, 25, axis=0)
q3 = np.percentile(matriz, 75, axis=0)

In [55]:
iqr = q3 - q1

In [56]:
linf = q1 - 1.5*iqr

lsup = q3 + 1.5*iqr

In [57]:
sin_outliers = np.all((matriz >= linf) & (matriz <= lsup), axis=1)

In [59]:
matriz_limpia = matriz[sin_outliers]

matriz_limpia

array([[100,  76,  81, 144, 113],
       [ 59, 136, 114,  67,  85],
       [146,  86,  92, 101,  57],
       [144, 103, 112, 128, 149],
       [ 80,  90,  84,  92,  52],
       [122,  88, 112,  96, 142],
       [116, 124,  59,  80, 137],
       [ 94, 135,  56,  53,  89],
       [127, 125, 134, 148,  96],
       [ 62,  84,  55, 141, 136],
       [134, 104,  93, 110, 145],
       [ 77,  81,  71, 141,  81],
       [ 66,  53,  68,  71,  59],
       [119, 127, 108,  82,  75],
       [150,  65, 137,  62,  92],
       [ 72,  74,  92,  70, 115],
       [123, 128, 103, 141,  95],
       [ 97, 105, 130, 107, 145],
       [ 99,  64,  56, 140, 123],
       [146,  71, 126, 116,  73],
       [117, 128, 119,  70, 114],
       [ 59,  51,  63, 117,  82],
       [ 72, 102, 143, 104,  97],
       [145, 128, 144,  64,  81],
       [ 87,  53, 119, 135,  81],
       [ 54, 135,  64,  96,  91],
       [ 87,  80,  62,  90, 107],
       [139,  73, 145,  79,  83],
       [108, 125,  61, 102,  84],
       [101,  

[np.float64(0.0),
 np.float64(0.1875),
 np.float64(0.3125),
 np.float64(0.625),
 np.float64(1.0)]

In [2]:
matriz = [[7,8,9],[10,11,12],[15,16,17]]

matriz[0][0] = 1

matriz

matriz_2 = np.array([[1,2,3,4],[4,5,6,7],[9,10,11,12],[13,14,15,16]])

matriz_2*2

matriz_2

NameError: name 'np' is not defined

## 4. Desafío


Eres el encargado de un almacén de productos electrónicos. Tienes un registro de ventas semanales para teléfonos, laptops y tabletas. Necesitas analizar las ventas para mejorar la gestión.

- Crea tres listas: una para teléfonos, otra para laptops y otra para tabletas con las ventas de cada día durante una semana.
- Usa slicing para obtener las ventas de los últimos 3 días de cada producto.
- Usa listas por comprensión para calcular el total de ventas de cada producto y el promedio de ventas diarias.
- Clasifica los productos en "ventas altas" o "ventas bajas" según si el promedio de ventas es mayor o menor a 5.

Instrucciones:
Usa sum() y len() para calcular el total de ventas y el promedio.
Clasifica las ventas usando listas por comprensión.

---

# Gracias por completar este laboratorio!

---