<a href="https://colab.research.google.com/github/gianmarcomejia96/UTEC_PROGRA/blob/main/03_estructuras_de_datos_parte2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


<img src="https://www.ctic.uni.edu.pe/wp-content/uploads/2022/04/588px-x-348px-web-1.png" alt="HTML5 Icon" width="900" height="350" >


<h1 align=center><font size = 5>ESTRUCTURAS DE DATOS - PARTE 2
</font></h1>

---


**Tabla de Contenidos**

- Diccionarios
- Sets
- Matrices

---

## 1. Diccionarios

**Concepto:**

Un diccionario es una estructura de datos que almacena pares clave-valor. Las claves deben ser únicas y se utilizan para acceder a los valores asociados.

### Ejemplo 1.1: Creación de Diccionarios y Acceso a Elementos


In [ ]:
# Crear un diccionario
persona = {'nombre': 'Ana', 'edad': 30, 'ciudad': 'Lima'}
print(persona)

{'nombre': 'Ana', 'edad': 30, 'ciudad': 'Lima'}


In [ ]:
persona = {'nombre':'Gianmarco','edad':30,'ciudad':'Lima'}

persona['nombre']

del persona['nombre']

persona

persona['nombre'] = 'Gianmarco'

persona

persona.get('Gianmarco')

In [ ]:
persona.get('edad')

30

In [ ]:
# Acceder a un valor
print("Nombre:", persona['nombre'])
print("Ciudad:", persona.get('ciudad'))


Nombre: Gianmarco
Ciudad: Lima


In [ ]:

# Añadir un nuevo par clave-valor
persona['profesion'] = 'Ingeniera'
print(persona)



In [ ]:
# Eliminar un par clave-valor
del persona['ciudad']
print(persona)

{'edad': 30, 'nombre': 'Gianmarco'}


### Ejemplo 1.2: Métodos Útiles de Diccionarios


In [ ]:
# Obtener todas las claves
print(persona.keys())


dict_keys(['edad', 'ciudad', 'nombre'])


In [ ]:
# Obtener todos los valores
print(persona.values())


dict_values([30, 'Lima', 'Gianmarco'])


dict_values([30, 'Lima', 'Gianmarco'])

In [ ]:
features_describe = {'pas_avg12': 'Ahorros promedio de la persona en los últimos meses', 'age':'Edad de la persona recogida de reniec','dist':'Distrito de residencia declarado por el cliente en última llamada'}

In [ ]:
features_describe['age']

'Edad de la persona recogida de reniec'

In [ ]:
persona.items()

dict_items([('edad', 30), ('nombre', 'Gianmarco')])

In [ ]:
for key, value in persona.items():
    print(key,value)

edad 30
nombre Gianmarco


In [ ]:
resumen = {
    "edad": 35.6,
    "ingreso": 10500.0,
    "hijos": 2.1
}

In [ ]:
for key, value in resumen.items():
  print(f' el promedio de {key} es: {value}')

 el promedio de edad es: 35.6
 el promedio de ingreso es: 10500.0
 el promedio de hijos es: 2.1


In [ ]:
template = "Hola {nombre}, tu edad es {edad} y vivís en {ciudad}."
datos = {
    "nombre": "Luis",
    "edad": 30,
    "ciudad": "Córdoba"
}

for key,value in datos.items():
    template = template.replace("{"+ key + "}",str(value))

template

'Hola Luis, tu edad es 30 y vivís en Córdoba.'

In [ ]:
template.format(**datos)

'Hola Luis, tu edad es 30 y vivís en Córdoba.'

In [ ]:
# Comprobar si una clave existe en el diccionario
if 'edad' in persona:
    print("La clave 'edad' está en el diccionario.")





La clave 'edad' está en el diccionario.


In [ ]:
persona['edad']

30

### Ejercicio 1: Trabajando con Diccionarios

- Crea un diccionario que contenga información sobre un automóvil (marca, modelo, año, color).
- Accede a cada valor usando su clave.
- Añade una clave para el precio del automóvil.
- Elimina la clave del color del automóvil y muestra el diccionario actualizado.
- Usa keys() y values() para imprimir las claves y valores del diccionario.



In [29]:
automovil = {'marca':'changan','modelo':'cs35 plus','color':'blanco'}

automovil.values()
automovil.keys()

print(f'estas son {automovil['marca']} {automovil['modelo']} {automovil['color']}')

automovil['precio'] = 18000

automovil.values()

del automovil['color']

automovil

for key, value in automovil.items():
  print(f' el diccionario contiene {key} : {value}')


estas son changan cs35 plus blanco
 el diccionario contiene marca : changan
 el diccionario contiene modelo : cs35 plus
 el diccionario contiene precio : 18000


## 2. Sets

Los sets son colecciones de elementos únicos y desordenados. Son útiles para eliminar duplicados o realizar operaciones matemáticas como intersección y unión.

### Ejemplo 2.1: Creación y Modificación de Sets

In [1]:
# Crear un set
numeros = {1, 2, 3, 4, 5}
print(numeros)


{1, 2, 3, 4, 5}


In [12]:
my_set = {1,2,3,4}


my_set2 = set((1,2,3,5))

print(my_set)
print(my_set2)

lista = [1,1,2,3]

lista_set = set(lista)

print(lista_set)


{1, 2, 3, 4}
{1, 2, 3, 5}
{1, 2, 3}


In [22]:
lista = ['aa','aa']

set_lista = set((lista))

print(set_lista)

list(set_lista)
print(set_lista)

{'aa'}
{'aa'}


In [32]:
lista_1 = ['columna1', 'columna2', 'columna3']
lista_2 = ['columna1', 'columna2', 'columna5']


list(set(lista_1+lista_2))


['columna3', 'columna1', 'columna2', 'columna5']

In [33]:
# Añadir elementos
numeros.add(6)
print(numeros)


{1, 2, 4, 5, 6}


In [35]:
# Eliminar un elemento
numeros.remove(2)
print(numeros)


{1, 4, 5, 6}


### Ejemplo 2.2: Operaciones de Conjuntos


In [36]:
# Crear otro set
otro_set = {4, 5, 6, 7}

In [37]:
# Unión de sets (todos los elementos)
union = numeros.union(otro_set)
print("Unión:", union)


Unión: {1, 4, 5, 6, 7}


In [38]:
# Intersección de sets (elementos comunes)
interseccion = numeros.intersection(otro_set)
print("Intersección:", interseccion)


Intersección: {4, 5, 6}


### Ejercicio 2: Operaciones con Sets

- Crea dos sets de números: uno con números del 1 al 10 y otro con números del 5 al 15.
- Encuentra la intersección y unión de ambos sets.
- Elimina un número del primer set.
- Usa un set para almacenar los nombres de tus amigos. Asegúrate de que no haya duplicados.

In [48]:

lista_1 = list(set([x for x in range(1,11)]))

lista_2 = list(set([x for x in range(5,16)]))

print(lista_1)
print(lista_2)

lista_1.remove(2)
lista_1

nombres = []

while True:
    nombre = input('ingrese nombres: ')
    if nombre == 'exit':
      break
    else:
     nombres.append(nombre)




[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
ingrese nombres: carlos
ingrese nombres: gian
ingrese nombres: omar
ingrese nombres: juan
ingrese nombres: gian
ingrese nombres: carlos
ingrese nombres: exit


In [51]:
nombres

nombres_finales = set(nombres)

nombres_finales

{'carlos', 'gian', 'juan', 'omar'}

## 3. Matrices

En Python, las matrices pueden representarse como listas de listas. Para manipular matrices más avanzadas y realizar cálculos eficientes, utilizamos la librería NumPy.

### Ejemplo 3.1: Matrices con Listas de Listas


In [52]:
# Crear una matriz 3x3 con listas anidadas
matriz = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
print(matriz)


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [60]:
# Acceder a elementos de la matriz
print("Elemento en [1][1]:", matriz[1][1])

matriz[1][2] = 2

matriz


Elemento en [1][1]: 5


[[1, 2, 3], [4, 5, 2], [10, 8, 9]]

In [58]:
}# Modificar un elemento
matriz[2][0] = 10
print(matriz)

[[1, 2, 3], [4, 5, 6], [10, 8, 9]]


### Ejemplo 3.2: Manipulación de Matrices con NumPy


In [66]:
import numpy as np

# Crear una matriz 3x3 con NumPy
matriz_np = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(matriz_np)




[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [67]:
# Sumar 10 a cada elemento
print(matriz_np + 10)



[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [68]:
# Multiplicar cada elemento por 2
print(matriz_np * 2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


### Ejercicio 3: Operaciones con Matrices

- Crea una matriz 3x3 usando listas de listas.
- Modifica un valor de la matriz y muestra la matriz actualizada.
- Usa NumPy para crear una matriz 4x4 con números aleatorios enteros.
- Realiza una operación de suma con la matriz (suma 5 a cada elemento).
- Multiplica los elementos de la matriz por 2 usando NumPy.

In [75]:
matriz = [[7,8,9],[10,11,12],[15,16,17]]

matriz[0][0] = 1

matriz

matriz_2 = np.array([[1,2,3,4],[4,5,6,7],[9,10,11,12],[13,14,15,16]])

matriz_2*2

matriz_2

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

## 4. Desafío


Eres el encargado de un almacén de productos electrónicos. Tienes un registro de ventas semanales para teléfonos, laptops y tabletas. Necesitas analizar las ventas para mejorar la gestión.

- Crea tres listas: una para teléfonos, otra para laptops y otra para tabletas con las ventas de cada día durante una semana.
- Usa slicing para obtener las ventas de los últimos 3 días de cada producto.
- Usa listas por comprensión para calcular el total de ventas de cada producto y el promedio de ventas diarias.
- Clasifica los productos en "ventas altas" o "ventas bajas" según si el promedio de ventas es mayor o menor a 5.

Instrucciones:
Usa sum() y len() para calcular el total de ventas y el promedio.
Clasifica las ventas usando listas por comprensión.

---

# Gracias por completar este laboratorio!

---