<a href="https://colab.research.google.com/github/gianmarcomejia96/UTEC_PROGRA/blob/main/manejo_de_archivos_modulos_y_paquetes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src="https://posgrado.utec.edu.pe/sites/default/files/2023-08/Testimonial-home-2.jpg" alt="HTML5 Icon" width="900" height="250" >


# **Funciones y Clases**

**Objetivo**

Consolidar los conocimientos sobre funciones y clases en Python, mediante el desarrollo de teoría, ejemplos guiados y ejercicios retadores. Al finalizar, serás capaz de:

1. Comprender qué son las funciones, cómo se definen y cómo se utilizan.
2. Usar distintos tipos de argumentos (posicionales, por nombre, arbitrarios).
3. Retornar valores simples o compuestos desde una función.
4. Aplicar funciones sobre listas y modularizar código en módulos.
5. Documentar y estructurar funciones siguiendo buenas prácticas de estilo.
6. Crear clases, instanciar objetos, y trabajar con atributos y métodos.
7. Aplicar principios de herencia y reutilización de código en clases.
8. Utilizar la biblioteca estándar de Python y organizar clases en módulos.

# Funciones

## 1. Defining a Function

- Las funciones encapsulan código reutilizable.
- Se definen usando 'def' seguido de un nombre y paréntesis.
- El cuerpo debe estar indentado.

**Ejemplo:**


In [ ]:
def saludar():
    print("Bienvenido al laboratorio de funciones.")


**Ejercicios:**

1. Crea una función 'mostrar_menu()' que imprima un menú con 3 opciones.

2. Define una función 'mensaje_diario()' que imprima una frase aleatoria de motivación.

3. Crea una función 'borde_decorativo()' que imprima una cadena rodeada de asteriscos.

📊 Ejercicio 1: Dataset personalizable

Objetivo: Crear una clase Dataset que almacene datos en forma de array NumPy.

🔧 Qué debe hacer:

Tener atributos: nombre, datos (una matriz NumPy)

Un método resumen() que imprima:

el nombre del dataset

cantidad de filas y columnas

media por columna

💡 Teoría de apoyo:

Usa self.datos.shape para filas/columnas

Usa np.mean(self.datos, axis=0) para promedios por columna

In [ ]:
import numpy as np
class Dataset:
  def __init__(self,nombre,datos):
    self.nombre = nombre
    self.datos = np.array(datos)

  def resumen(self):
    print(f' el nombre es {self.nombre}')
    print(f' cantidad de filas y columnas {self.datos.shape}')
    print(f'la media por columna es :{np.mean(self.datos,axis=0)}')





In [ ]:
Dataset('hola',np.random.randint(0,100,size = (4,4) )).resumen()


 el nombre es hola
 cantidad de filas y columnas (4, 4)
la media por columna es :[64.75 30.75 40.   77.  ]


In [10]:
class Car:
    def drive(self):
      print("the car is moving")



In [11]:
my_car = Car()

In [12]:
my_car.drive()

the car is moving


🧠 Ejercicio 3: Validador de outliers

Objetivo: Crear una clase OutlierDetector que detecte y filtre outliers por columna usando el método IQR.

🔧 Qué debe hacer:

Recibir un array NumPy en el constructor

Tener un método .filtrar() que devuelva solo las filas sin outliers

Usar el método del rango intercuartil (IQR)

💡 Teoría de apoyo:

Cálculo IQR por columna:

In [41]:
class OutlierDetector_:
    def __init__(self,datos):
      self.datos = np.array(datos)

    def filtrar(self):
      q1 = np.percentile(self.datos,25,axis=0)
      q3 = np.percentile(self.datos,75,axis=0)
      iqr = q3-q1
      linf = q1 - 1.5*iqr
      lsup = q3 + 1.5*iqr
      mask = np.all((self.datos>=linf) & (self.datos<=lsup),axis = 0)
      return self.datos[mask]



In [42]:
import numpy as np

data = np.array([
    [10, 200],
    [15, 180],
    [20, 220],
    [25, 210]
])

In [53]:
class Scaler:
    def __init__(self,data):
      self.data = data

    def normalize(self):
      normalized = (self.data - self.data.min())/ (self.data.max() - self.data.min())
      return normalized



In [72]:
data = np.random.randint(0,100,size=(5,5))
data

array([[43, 94, 40, 57, 78],
       [97, 64, 35, 96, 99],
       [51, 52, 36, 61, 88],
       [92, 17, 83, 64, 21],
       [23, 87, 25, 39, 43]])

In [52]:
class Student:
    def __init__(self, name, age, major):
        self.name = name
        self.age = age
        self.major = major
    def info(self):
        print(f'{self.name} is {self.age} years old and studies {self.major}.')


In [57]:
S = Scaler(data)

In [62]:
class Rectangle:
    def __init__(self,width,height):
        self.width = width
        self.height = height
    def area(self):
        calculo = self.width * self.height
        return calculo


In [64]:
d = Rectangle(20,40).area()
d

800

In [67]:
import math
math.pi

3.141592653589793

👣 Action Step (Before Day 7):
Create a class Circle
Store the radius in __init__
Add a method area() that returns the circle's area
💡 Use this formula: area = π * radius² (you can use math.pi)

In [69]:
class Circle:
    def __init__(self, r):
        self.r = r
    def area(self):
        calculo =  math.pi * self.r **2
        return calculo


In [71]:
d = Circle(0.5).area()
d

0.7853981633974483

In [59]:
S.normalize()

array([[0.        , 0.9047619 ],
       [0.02380952, 0.80952381],
       [0.04761905, 1.        ],
       [0.07142857, 0.95238095]])

In [39]:
s1 = Student("Alice", 22, "Data Science")

In [40]:
s1.info()

Alice is 22 years old and studies Data Science.


In [ ]:
data = np.random.randint(0,100,size=(5,5))
data

array([[84, 78, 95, 13,  4],
       [14, 76,  8, 96, 60],
       [77, 79, 36,  5, 76],
       [78, 26, 93, 90, 93],
       [ 1, 94, 16, 13, 64]])

In [ ]:
OutlierDetector_(data).filtrar()

array([[84, 78, 95, 13,  4],
       [77, 79, 36,  5, 76],
       [78, 26, 93, 90, 93]])

In [73]:
import json

texto = '{"nombre": "Alice", "edad": 25}'
persona = json.loads(texto)

print(persona["nombre"])

Alice


In [74]:
info = {"curso": "Python", "nivel": "básico"}
texto_json = json.dumps(info)

print(texto_json)  # {"curso": "Python", "nivel": "básico"}

{"curso": "Python", "nivel": "b\u00e1sico"}


In [ ]:
import string


In [ ]:
class Clasificador:
  def __init__(self,texto):
    self.texto_original = texto
    self.palabras = self.preprocesar(texto)

  def preprocesar(self,texto):
    texto = texto.lower()
    for signo in string.punctuation:
      texto = texto.replace(signo,"")
    return texto.split()

  def unicos(self):
      return set(self.palabras)

  def palabra_mas_frecuente(self):
      conteo = {}
      for palabra in self.palabras:
          conteo[palabra] = conteo.get(palabra, 0) + 1
      max_palabra = max(conteo, key=conteo.get)
      return max_palabra

  def buscar_palabras(self,subcadena):
      words = self.palabras
      matching_words =  set([word for word in words if subcadena.lower() in word])
      return matching_words



In [ ]:
a = Clasificador("Esto no puede ser posible, no querias comer, no fuiste")
print(a.palabra_mas_frecuente())

no


In [ ]:
a = Clasificador("sol solsticio, amen, amenazaa, droga, drogadicto y solsticio, drogadicto")
print(a.buscar_palabras("dro"))

{'drogadicto', 'droga'}


In [ ]:
palabras = ["sol", "luna", "sol", "estrella", "luna", "sol"]
conteo = {}




In [ ]:
for palabra in palabras:
  conteo[palabra] = conteo.get(palabra,0)+1


In [ ]:
conteo

{'sol': 3, 'luna': 2, 'estrella': 1}

In [ ]:
maximo = max(conteo,key=conteo.get)
maximo

ValueError: max() iterable argument is empty

In [ ]:
a = Clasificador("python es genial y python es divertido")
print(a.palabra_mas_frecuente())

python


📊 Ejercicio 2: Normalizador de columnas

Objetivo: Crear una clase Normalizador para normalizar columnas numéricas de una matriz.

🔧 Qué debe hacer:

Recibir un array NumPy en el constructor

Tener un método normalizar() que:

aplique normalización min-max por columnas

devuelva el nuevo array normalizado

💡 Teoría de apoyo:

Normalización Min-Max:

𝑥
𝑛
𝑜
𝑟
𝑚
=
𝑥
−
min
⁡
max
⁡
−
min
⁡
x
norm
	​

=
max−min
x−min
	​


In [ ]:
class Normalizador:
  def __init__(self,datos):
    self.datos = np.array(datos)
  def normalizar(self):
    min = np.min(self.datos,axis=0)
    max = np.max(self.datos,axis=0)
    resultado = (self.datos - min) / (max- min)
    return resultado

In [ ]:
data = np.random.randint(0,100,size=(2,2))

In [ ]:
Normalizador(data).normalizar()


array([[0., 1.],
       [1., 0.]])

## 2. Passing Arguments

- Puedes pasar información a las funciones mediante parámetros.
- Argumentos posicionales: el orden importa.
- Argumentos por nombre (keyword arguments): más claros y seguros.

**Ejemplo:**

In [ ]:
def presentar(nombre, edad):
    print(f"Hola, soy {nombre} y tengo {edad} años.")

**Ejercicios:**

1. Define 'calcular_impuesto(monto, tasa)' que retorne el impuesto total.

2. Crea 'evaluar_puntaje(nombre, puntaje)' que imprima si aprueba (>=12) o no.

3. Escribe 'detallar_producto(nombre, precio, stock)' que imprima un resumen.

In [ ]:

def calcular_impuesto(monto,tasa):
    impuesto = monto * tasa
    return (f' el impuesto fue de {impuesto} nuevos soles')


In [ ]:
calcular_impuesto(100,0.18)

' el impuesto fue de 18.0 nuevos soles'

In [ ]:
def evaluar_puntaje(nombre,puntaje):
    if puntaje >= 12:
      resultado = "Aprueba"
    else:
      resultado = "Desaprueba"
    return print(f'{nombre} {resultado} ')

In [ ]:
def detallar_producto(nombre,precio,stock):
    resultado = print(f'el producto seleccionado es {nombre}, cuesta {precio} y hay {stock} unidades')
    return resultado


In [ ]:
detallar_producto('papa',20,2)

el producto seleccionado es papa, cuesta 20 y hay 2 unidades


In [ ]:
evaluar_puntaje('gianmarco',13)

gianmarco Aprueba 


## 3. Return Values

- Las funciones pueden devolver valores con 'return'.
- Es útil para guardar o reutilizar resultados.

**Ejemplo:**


In [ ]:
def cuadrado(numero):
    return numero ** 2

**Ejercicios:**

1. 'diferencia_absoluta(a, b)' que retorne el valor absoluto de su diferencia.

2. 'comparar_cadenas(cad1, cad2)' que retorne True si tienen la misma longitud.

3. 'es_primo(n)' que retorne True si el número es primo.

## 4. Passing a List

- Las funciones pueden recibir listas para iterar, modificar o procesar.


**Ejemplo:**

In [ ]:
def imprimir_nombres(lista):
    for nombre in lista:
        print(f"- {nombre}")

**Ejercicios:**

1. 'invertir_lista(lista)' que retorne la lista invertida.

2. 'sumar_pares(lista)' que sume solo los números pares.

3. 'normalizar_textos(lista)' que convierta todo texto a minúsculas y sin espacios.

## 5. Passing Arbitrary Number of Arguments


- *args permite recibir cualquier número de argumentos posicionales.
- **kwargs permite recibir pares clave-valor (keyword args).

**Ejemplo:**

In [ ]:
def sumar_todo(*numeros):
    return sum(numeros)

**Ejercicios:**

1. 'registrar_evento(nombre, *participantes)' que imprima el evento y los asistentes.

2. 'generar_reporte(**datos)' que imprima claves y valores con formato.

3. 'concatenar_textos(*cadenas)' que retorne el texto unificado, separado por guiones.

In [ ]:
def concatenar(*cadenas):
  return '-'.join(cadenas)

concatenar('bienvenidos','al', 'curso')

'bienvenidos-al-curso'

## 6. Storing Functions in Modules

- Guardar funciones en archivos .py permite modularidad y reutilización.
- Luego se importa el archivo usando 'import'.

**Ejemplo (módulo: utilidades.py):**

In [ ]:
# def saludar():
#     print("Hola desde utilidades")
#
# En main.py:
# import utilidades
# utilidades.saludar()

In [ ]:
from nuevo import sumar_todo

In [ ]:
sumar_todo(100,200)

300

In [ ]:
import nuevo

**Ejercicios:**

1. Crea un módulo 'texto_utils.py' con funciones para contar palabras, quitar tildes y convertir a minúsculas.

2. Crea un módulo 'calculadora.py' con funciones básicas y una función especial: factorial.

3. Importa y usa ambos módulos en un script principal.

# Clases

## 1. Creating and Using a Class

- Las clases son plantillas para crear objetos.
- Usan __init__() para inicializar atributos.

**Ejemplo:**


In [ ]:
class Persona:
    def __init__(self, nombre, edad):
        self.nombre = nombre
        self.edad = edad

    def saludar(self):
        print(f"Hola, soy {self.nombre}.")

**Ejercicios:**

1. Crea la clase 'Libro' con atributos titulo, autor y año.

2. Crea 'CuentaBancaria' con saldo inicial y métodos para depositar y retirar.

3. Define 'Pelicula' con método 'resumen()' que imprima una sinopsis.

In [ ]:
class Libro:
    def __init__(self,titulo,autor,anio):
      self.titulo = titulo
      self.autor = autor
      self.anio = anio

    def resumen(self):
      print(f'el libro es {self.titulo} del {self.autor} y se publicó en el año {self.anio}')



In [ ]:
mi_libro = Libro('sherlock','aa',2008)

mi_libro.resumen()

el libro es sherlock del aa y se publicó en el año 2008


## 2. Working with Classes and Instances

- Cada objeto instanciado es independiente.
- Puedes modificar atributos directamente o con métodos.

**Ejemplo:**


In [ ]:
juan = Persona("Juan", 28)
juan.saludar()

**Ejercicios:**

1. Crea múltiples instancias de una clase 'Jugador' y cámbiales puntaje.

2. Añade un método 'actualizar_email' a una clase 'Usuario'.

3. Añade método 'subir_nivel()' que incremente un atributo nivel.

## 3. Inheritance

- Las clases pueden heredar atributos y métodos de otras.
- La subclase puede extender o sobreescribir métodos.

**Ejemplo:**

In [ ]:
class Animal:
    def __init__(self, especie):
        self.especie = especie

    def hablar(self):
        print("Este animal hace un sonido")

class Perro(Animal):
    def hablar(self):
        print("Guau")

**Ejercicios:**

1. Crea 'Empleado' y 'Gerente' que herede e incluya equipo a cargo.

2. Crea 'Vehiculo' y subclases 'Auto', 'Moto', con métodos específicos.

3. 'Cuenta' y subclases 'CuentaAhorro', 'CuentaCorriente' con comisiones.

In [ ]:
class Empleado:
    def __init__(self,nombre):
      self.nombre = nombre

class Gerente:
    def __init__(self,nombre,Empleado):
      self.nombre = nombre
      self.Empleado = Empleado


class jerarquia:
    def __init__(self,Empleado,Gerente):
      self.Gerente = Gerente
      self.Empleado = Empleado

    def resumen(self):
      print(f'hola soy {self.Gerente.nombre} y mi subordinado es {self.Empleado.nombre}')



In [ ]:
# ✅ Ejercicio 1: Persona con edad

#Crea una clase Persona que reciba nombre y edad.
#Luego, imprime ambos valores desde un objeto.

In [ ]:
class Persona:
  def __init__(self,nombre,edad):
    self.nombre = nombre
    self.edad = edad
  def resumen(self):
    print(self.nombre)
    print(self.edad)


Persona("gian",27).resumen()


gian
27


In [ ]:
#✅ Ejercicio 2: Animal que hace sonido

#Crea una clase Animal que reciba nombre y sonido.
#Agrega un método hablar() que imprima algo como:
#Soy un [nombre] y hago "[sonido]"

In [ ]:
class Animal:
    def __init__(self,nombre,sonido):
      self.nombre = nombre
      self.sonido = sonido
    def hablar(self):
      print(f'soy un {self.nombre} y hago {self.sonido}')


Animal('perro','guau').hablar()


soy un perro y hago guau


✅ Ejercicio 1: Fila de Datos

Crea una clase FilaDatos que reciba 3 atributos:

id (número)

nombre (texto)

valor (número)

Y agrega un método mostrar() que imprima los datos en este formato:
ID: 1 - Nombre: Juan - Valor: 56.4

In [ ]:
class Filadatos:
  def __init__(self,id,nombre,valor):
    self.id = int(id)
    self.nombre = str(nombre)
    self.valor = float(valor)

  def a_dict(self):
      return {
          'id':self.id,
          'nombre':self.nombre,
          'valor': self.valor
      }

Filadatos(1,"Juan",56.4).a_dict()

{'id': 1, 'nombre': 'Juan', 'valor': 56.4}

In [ ]:
class FilaDatos:
    def __init__(self, **kwargs):
        for clave, valor in kwargs.items():
            setattr(self, clave, valor)

    def a_dict(self):
        return self.__dict__

In [ ]:
class FilaDatos:
    def __init__(self,**kwargs):
      for clave, valor in kwargs.items():
        setattr(self,clave,valor)

    def a_dict(self):
        return self.__dict__
FilaDatos(id=1,nombre="juan",valor=56.4).a_dict()

{'id': 1, 'nombre': 'juan', 'valor': 56.4}

✅ EJERCICIO 2: Clase TablaDatos

Crea una clase llamada TablaDatos que:

Reciba una lista de objetos FilaDatos

Tenga un método a_lista_dicts() que devuelva una lista de diccionarios, usando .a_dict() de cada fila

💡 Pistas:

Guarda la lista en self.filas

Usa un bucle para convertir cada objeto con .a_dict()

In [ ]:
class FilaDatos:
    def __init__(self,**kwargs):
      for clave,valor in kwargs.items():
          setattr(self,clave,valor)
    def a_dict(self):
      return self.__dict__
class TablaDatos:
    def __init__(self,filas):
      self.filas = filas
    def a_lista_dicts(self):
        resultado = []
        for fila in self.filas:
          resultado.append(fila.a_dict())
        return resultado




In [ ]:
f1 = FilaDatos(id=1, nombre="Ana", valor=10)
f2 = FilaDatos(id=2, nombre="Luis", valor=20)
f3 = FilaDatos(id=3, nombre="Carlos", valor=15.5)

In [ ]:
tabla = TablaDatos([f1, f2, f3]).a_lista_dicts()
print(tabla)

[{'id': 1, 'nombre': 'Ana', 'valor': 10}, {'id': 2, 'nombre': 'Luis', 'valor': 20}, {'id': 3, 'nombre': 'Carlos', 'valor': 15.5}]


1. Dato: Clase base para representar un dato numérico.

Subclase DatoEntero: asegura que el valor sea un entero.

Subclase DatoDecimal: asegura que el valor sea un decimal (float).

Método mostrar_valor() que imprime el tipo y el valor.

📌 Objetivo: practicar __init__ y herencia básica

In [ ]:
class Dato:
  def __init__(self,valor):
    self.valor = valor
  def mostrar_valor(self):
     print(f'Soy un dato con valor: {self.valor}')

class DatoEntero(Dato):
    def __init__(self,valor):
      if not isinstance(valor,int):
        raise ValueError("no has insertado un valor valido")
      super().__init__(valor)

class DatoDecimal(Dato):
    def __init__(self,valor):
      if not isinstance(valor,float):
        raise ValueError("no has insertado un valor valido")
      super().__init__(valor)






In [ ]:
DatoDecimal(2.2).mostrar_valor()

Soy un dato con valor: 2.2


## 4. Importing Classes

- Puedes importar clases específicas con 'from modulo import Clase'.


**Ejemplo:**

from persona import Persona


**Ejercicios:**

1. Guarda tu clase 'Libro' en un archivo y úsala desde otro script.

2. Importa múltiples clases desde un solo módulo.

3. Reorganiza tu código en paquetes (carpetas con __init__.py).

## 5. The Python Standard Library


- La biblioteca estándar incluye módulos como random, datetime, os, math.


**Ejemplo:**



In [ ]:
import random
print(random.randint(1, 10))

**Ejercicios:**

1. Usa datetime para imprimir la fecha de nacimiento a partir de edad.

2. Usa os para listar todos los archivos de un directorio.

3. Usa math para resolver la fórmula cuadrática.

---

# Gracias por completar este laboratorio!

---
